import { Inter } from "next/font/google";
import "./globals.css";
import CartProvider from "@/providers/cart-provider";
import ShoppingCartModal from "@/components/modals/shopping-cart-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
      <body className={inter.className}>
            <ShoppingCartModal/>
             {children}
          
         </body>
         </CartProvider>
    </html>
  );
}
